services:

  mysql:
    image: mysql:8
    
  fastapi:
    image: ${ECR}:fastapi

  django:
    image: ${ECR}:django

  node:
    image: ${ECR}:node

  dotnet:
    image: ${ECR}:dotnet

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"