events {}

http {
    log_format custom '$remote_addr - "$request" '
                      '→ service: $upstream_addr';

    access_log /var/log/nginx/access.log custom;



    upstream backend_servers {
        server fastapi-app:8001;
        server django-app:8002;
        server node-app:8003;
        server dotnet-app:8004;
    }

    server {
        listen 80;


        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }

        location /fastapi/ {
            rewrite ^/fastapi/(.*)$ /$1 break;
            # proxy_pass http://fastapi:8001;
            proxy_pass http://backend_servers;

            proxy_set_header Host $host;
        }

        location /django/ {
            rewrite ^/django/(.*)$ /$1 break;
            # proxy_pass http://django:8002;
            proxy_pass http://backend_servers;


            proxy_set_header Host $host;   # 🔥 THIS FIXES YOUR ERROR
        }

        location /node/ {
            rewrite ^/node/(.*)$ /$1 break;
            # proxy_pass http://node:8003;
            proxy_pass http://backend_servers;


            proxy_set_header Host $host;
        }

        location /dotnet/ {
            rewrite ^/dotnet/(.*)$ /$1 break;
            # proxy_pass http://dotnet:8004;
            proxy_pass http://backend_servers;


            proxy_set_header Host $host;
        }
    }
}