events {}

http {
    # Log format for API requests only
    log_format api_log '$remote_addr - "$request" → Backend: $upstream_addr';
    
    # Separate access log for API
    access_log /var/log/nginx/access.log api_log;
    
    # Error log - Only errors
    error_log /var/log/nginx/error.log error;

    upstream backend_servers {
    server fastapi:8001 max_fails=3 fail_timeout=30s;
    server django:8002 max_fails=3 fail_timeout=30s;
    server node:8003 max_fails=3 fail_timeout=30s;
    server dotnet:8004 max_fails=3 fail_timeout=30s;
}
    

    server {
        listen 80;

        # Frontend static files - No logging
        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
            access_log off;  # Don't log static file requests
        }

        # API endpoint - Log only API requests
        location /api/ {
            rewrite ^/api/(.*) /$1 break;
            proxy_pass http://backend_servers;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            proxy_connect_timeout 10s;
            proxy_send_timeout 30s;
            proxy_read_timeout 30s;
        }
    }
}