events {}

http {

    log_format api_log '$remote_addr - "$request" → Backend: $upstream_addr';
    log_format main '$remote_addr - - [$time_local] "$request" $status';

    access_log /var/log/nginx/access.log main;
    error_log /var/log/nginx/error.log error;

    upstream backend_servers {
        server fastapi:8001;
        server django:8002;
        server node:8003;
        server dotnet:8004;
    }

    server {
        listen 80;

        location = /health {
            return 200 "OK";
            add_header Content-Type text/plain;
        }

        location /api/ {
            access_log /var/log/nginx/access.log api_log;
            rewrite ^/api/(.*) /$1 break;
            proxy_pass http://backend_servers\;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /api/fastapi/ {
            rewrite ^/api/fastapi/(.*) /$1 break;
            proxy_pass http://fastapi:8001\;
        }

        location /api/django/ {
            rewrite ^/api/django/(.*) /$1 break;
            proxy_pass http://django:8002\;
        }

        location /api/node/ {
            rewrite ^/api/node/(.*) /$1 break;
            proxy_pass http://node:8003\;
        }

        location /api/dotnet/ {
            rewrite ^/api/dotnet/(.*) /$1 break;
            proxy_pass http://dotnet:8004\;
        }

        location /prometheus/ {
            proxy_pass http://prometheus:9090/\;
            proxy_read_timeout 300s;
        }

        location /grafana/ {
            proxy_pass http://grafana:3000/\;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }

        location /alertmanager/ {
            proxy_pass http://alertmanager:9093/\;
        }

        location /nginx_status {
            stub_status on;
            access_log off;
            allow 127.0.0.1;
            allow 172.0.0.0/8;
            deny all;
        }

        location = / {
            return 200 "Backend is running 🚀";
        }
        
        location / {
            return 404 "Not Found";
        }
    }
}
